// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6GgO1fbAb7pjq3v6-lnBrAjStkTNwFu4',
    appId: '1:664949220313:web:78405ad6e41393b5eeefc8',
    messagingSenderId: '664949220313',
    projectId: 'trackademic-0',
    authDomain: 'trackademic-0.firebaseapp.com',
    storageBucket: 'trackademic-0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2cl8AmJLduQ4IaCbUf6gM59BeBWBfSuo',
    appId: '1:664949220313:android:80926990418f7d2aeeefc8',
    messagingSenderId: '664949220313',
    projectId: 'trackademic-0',
    storageBucket: 'trackademic-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDJ1qrUvygd-8CQD9WqXDrv84i8AMoUr8',
    appId: '1:664949220313:ios:667598c8f8a28c5aeeefc8',
    messagingSenderId: '664949220313',
    projectId: 'trackademic-0',
    storageBucket: 'trackademic-0.firebasestorage.app',
    iosBundleId: 'com.trackademic.trackademic',
  );
}
